demo/src/react-admin/modules/user-group/views/UserGroupOverview.tsx
=> feat(arc-515): add toasts to permissions

demo/src/modules/content-page/ContentPageDetailPage.tsx, demo/src/modules/content-page/ContentPageEditPage.tsx, demo/src/modules/content-page/ContentPageOverviewPage.tsx, demo/src/modules/content-page/content.routes.tsx, demo/src/react-admin/modules/content-page/views/ContentPageDetail.tsx, demo/src/react-admin/modules/content-page/views/ContentPageEdit.tsx, demo/src/react-admin/modules/content-page/views/ContentPageOverview.tsx, demo/src/react-admin/modules/shared/consts/routes.ts, demo/src/react-admin/modules/shared/layouts/AdminLayout/AdminLayout.types.ts
=> feat(arc-610): change content page routing to get id from parent

demo/src/modules/user/user.tsx, demo/src/react-admin/core/config/config.types.ts, demo/src/react-admin/modules/index.ts, demo/src/react-admin/modules/user/index.ts, demo/src/react-admin/modules/user/user.consts.ts, demo/src/react-admin/modules/user/views/UserOverview.tsx
- Export UserOverview
- Pass bulkActions through config
- Remove AdminLayout from component
=> fix(arc-594): pass bulk actions via config; export component

demo/src/index.tsx, demo/src/react-admin/modules/content-page/components/wrappers/PageOverviewWrapper/PageOverviewWrapper.tsx, demo/src/react-admin/modules/content-page/views/ContentPageOverview.tsx, demo/src/react-admin/modules/shared/types/authentication.types.ts
Requires proxy PR: https://github.com/viaacode/hetarchief-proxy/pull/193
=> feat(arc-611): Add page overview block for faq items

demo/src/index.tsx, demo/src/react-admin/core/config/config.types.ts, demo/src/react-admin/modules/content-page/components/ContentEditForm/ContentEditForm.tsx, demo/src/react-admin/modules/shared/components/ContentPicker/ContentPicker.tsx, demo/src/react-admin/modules/shared/components/ContentPicker/item-providers/internal-link.ts, package-lock.json, package.json
=> fix(arc-154): fix static links dropdowns

demo/src/react-admin/modules/user-group/const/user-group.const.tsx, demo/src/react-admin/modules/user-group/views/UserGroupOverview.tsx
order colunms:
only search label, don't search description nor name
=> fix(arc-596): sort columns user groups, only search in label

demo/src/index.tsx, demo/src/react-admin/modules/content-page/components/ContentPage/ContentPage.tsx, demo/src/react-admin/modules/content-page/components/blocks/intro.ts, demo/src/react-admin/modules/content-page/types/content-block.types.ts
=> fix(arc-997): enable heading type for intro

demo/src/index.tsx, demo/src/react-admin/core/config/config.types.ts, demo/src/react-admin/modules/content-page/components/ContentBlockPreview/ContentBlockPreview.tsx, demo/src/react-admin/modules/content-page/const/content-page.consts.ts, demo/src/react-admin/modules/content-page/helpers/content-edit.reducer.ts, demo/src/react-admin/modules/content-page/helpers/parsers.ts, demo/src/react-admin/modules/content-page/index.ts, demo/src/react-admin/modules/content-page/types/content-pages.types.ts
https://meemoo.atlassian.net/browse/ARC-1002
Note that the translations of meemoo do not match the namings in code (940px => LARGE in code => medium in translations)
```
contentPage: {
availableContentBlocks: [
ContentBlockType.Heading,
ContentBlockType.Intro,
ContentBlockType.RichText,
ContentBlockType.RichTextTwoColumns,
ContentBlockType.Buttons,
ContentBlockType.Image,
ContentBlockType.ImageGrid,
ContentBlockType.PageOverview,
ContentBlockType.UspGrid,
ContentBlockType.Quote,
],
defaultPageWidth: ContentWidth.LARGE,
},
```
=> feat(arc-1002): add config option to set default content page width

demo/src/react-admin/modules/content-page/components/blocks/quote.ts
- disable quote author validation
=> feat(content blocks): disable quote author validation

demo/src/index.tsx, demo/src/react-admin/core/config/config.types.ts, demo/src/react-admin/modules/content-page/views/ContentPageEdit.tsx
https://meemoo.atlassian.net/browse/ARC-1002
=> feat(arc-1002): add hook to notify consumer of a saved content page

demo/src/react-admin/modules/content-page/components/ContentPage/ContentPage.tsx
https://meemoo.atlassian.net/browse/ARC-1014
check for meemoo admin:
check for cp admin
check for regular visitor
check for kiosk visitor
check for logged out user
=> fix(arc-1014): correctly check user groups for each block

demo/src/react-admin/generated/graphql-db-types-avo.ts, demo/src/react-admin/generated/graphql-db-types-hetarchief.ts, demo/src/react-admin/modules/content-page/queries/avo/soft-delete-content.graphql, demo/src/react-admin/modules/content-page/queries/hetarchief/soft-delete-content.graphql, demo/src/react-admin/modules/content-page/services/content-page.service.ts
update path when soft deleting content page
=> fix(arc-1036): update path when soft deleting content page

demo/src/react-admin/modules/navigation/views/NavigationDetail.tsx
before this PR the deleted item would not be removed:
after this PR the item is correctly removed:
=> fix(arc-1043): refresh the navigation items after deleting a nav item

demo/src/react-admin/modules/content-page/components/ContentBlockForm/ContentBlockForm.tsx, demo/src/react-admin/modules/content-page/views/ContentPageEdit.tsx
Mirror of https://github.com/viaacode/avo2-client/pull/1595
=> feat(avo-2183): mirror changes for AvO

demo/src/react-admin/modules/content-page/views/ContentPageEdit.scss, demo/src/react-admin/modules/shared/components/FileUpload/FileUpload.scss
=> fix(ARC-1114): fix labels coming out of container

demo/src/react-admin/modules/content-page/views/ContentPageEdit.scss
=> fix(ARC-1115): expand sidebar

README.md
Note: this documentation is only relevant during the limbo-phase before the Admin Core track is wrapped up.
=> chore: add some docs

api/package.json, api/src/modules/content-pages/services/content-pages.service.ts, api/src/modules/permissions/controllers/permissions.controller.ts, api/src/modules/permissions/permissions.types.ts, api/src/modules/permissions/queries/avo/get-permissions.graphql, api/src/modules/permissions/services/permissions.service.ts, api/src/modules/player-ticket/services/player-ticket.service.ts, api/src/modules/shared/helpers/is-avo.ts, api/src/modules/shared/helpers/is-hetarchief.ts, api/src/modules/user-groups/controllers/user-groups.controller.ts, api/src/modules/user-groups/services/user-groups.service.ts, api/src/modules/user-groups/user-groups.types.ts, ui/package.json, ui/src/modules/user-group/user-groups.service.ts, ui/src/react-admin/core/config/config.types.ts, ui/src/react-admin/modules/permissions/types/permissions.types.ts, ui/src/react-admin/modules/user-group/const/user-group.const.tsx, ui/src/react-admin/modules/user-group/hooks/data/get-all-user-groups.ts, ui/src/react-admin/modules/user-group/mocks/index.ts, ui/src/react-admin/modules/user-group/types/user-group.types.ts, ui/src/react-admin/modules/user-group/views/UserGroupOverview.tsx
https://meemoo.atlassian.net/browse/AVO-2211
=> feat(avo-2211): fix issues with permission overview

api/src/modules/player-ticket/dto/GetPlayableUrlDto.dto.ts, api/src/modules/player-ticket/index.ts, api/src/modules/player-ticket/player-ticket.consts.ts, api/src/modules/player-ticket/player-ticket.controller.ts, api/src/modules/player-ticket/player-ticket.module.ts, api/src/modules/player-ticket/services/player-ticket.service.ts
https://meemoo.atlassian.net/browse/AVO-2192
=> feat(avo-2192): use player ticket service from admin-core

api/src/modules/shared/generated/graphql-db-types-hetarchief.ts, api/src/modules/users/users.consts.ts, api/src/modules/users/users.types.ts
=> feat(api-admin-user): add full name to sortColumn

ui/src/react-admin/modules/shared/helpers/formatters/date.ts, ui/src/react-admin/modules/user/components/TempAccessModal.tsx, ui/src/react-admin/modules/user/views/UserDetail.tsx
https://meemoo.atlassian.net/browse/AVO-2370
page: http://localhost:8080/admin/gebruikers/c1bee9a0-1918-47a4-99d0-6e68ec34a5c0
before:
after:
=> fix(avo-2370): correctly render tempAccess fields on user detail page

api/src/modules/users/users.converters.ts, api/src/modules/users/users.types.ts, ui/src/react-admin/modules/shared/helpers/formatters/avatar.tsx, ui/src/react-admin/modules/user/user.types.ts
https://meemoo.atlassian.net/browse/AVO-2373
page: http://localhost:8080/admin/gebruikers/69ccef3b-751a-4be4-95bc-5ef365fbd504
page: http://localhost:8080/instellingen
before:
after:
=> fix(avo-2373): add avatar to admin-core-api response

ui/src/index.tsx, ui/src/react-admin/modules/content-page/components/ContentPageRenderer/ContentPageRenderer.tsx, ui/src/react-admin/modules/content-page/services/content-page.converters.ts, ui/src/react-admin/modules/content-page/services/content-page.service.ts, ui/src/react-admin/modules/content-page/types/content-pages.types.ts, ui/src/react-admin/modules/content-page/views/ContentPageDetailMetaData.tsx, ui/src/react-admin/modules/content-page/views/ContentPageEdit.tsx
https://meemoo.atlassian.net/browse/AVO-2410
page: http://localhost:3400/admin/content/1578/bewerk
before:
after:
=> fix(avo-2410): convert rich text editor state to html before save

ui/src/react-admin/modules/user/views/UserDetail.tsx, ui/src/react-admin/modules/user/views/UserEdit.tsx
https://meemoo.atlassian.net/browse/AVO-2344
=> feat(avo-2344): remove alias fields from userDetail and userEdit screens

ui/src/react-admin/modules/content-page/components/ContentEditForm/ContentEditForm.tsx, ui/src/react-admin/modules/content-page/components/PublishContentPageModal.tsx, ui/src/react-admin/modules/content-page/helpers/content-edit.reducer.ts, ui/src/react-admin/modules/content-page/services/content-page.service.ts, ui/src/react-admin/modules/content-page/views/ContentPageDetail.tsx, ui/src/react-admin/modules/content-page/views/ContentPageEdit.tsx
https://meemoo.atlassian.net/browse/AVO-2393
before this used to just make the author dropdown default to the current user
=> fix(avo-2393): make the owner of a new content page the current user

api/src/modules/content-pages/services/content-pages.service.ts
https://meemoo.atlassian.net/browse/AVO-2421
Avo used to only contain numbers for user group ids: -1, -2, 1, 2, 3, ...
But since hetarchief also uses the admin-core, those user group ids are uuids in the hetarchief database, so string[]
Now at some point we want avo to also switch to strings: "-1", "-2", "1", "2", "3", ...
some of these arrays in the avo database are currently  "-1", "-2", "1", "2", "3", ... and some older pages are still -1, -2, 1, 2, 3, ...
So i had to change the query in this PR to handle _or string or number
This is not ideal, and we still might look into a migration script to convert all user group ids to strings in the future.
page: http://localhost:8080/nieuws
before:
after:
=> fix(avo-2421): handle both numeric and string user group ids

ui/package-lock.json, ui/package.json
https://meemoo.atlassian.net/browse/AVO-2396
bump avo2-components version to include the styles for the perfect-scrollbar library: https://github.com/viaacode/avo2-components/commit/e264a072f758bda3331ed9cc953c3f9501c8992d
before:
after:
=> fix(avo-2396): bump avo2-component version to fix modal scrollbars

api/src/modules/maintenance-alerts/queries/hetarchief-and-avo/update-maintenance-alert.graphql, api/src/modules/maintenance-alerts/services/maintenance-alerts.service.ts, api/src/modules/shared/generated/graphql-db-types-hetarchief.ts
**JIRA**
https://meemoo.atlassian.net/browse/ARC-1473
=> fix(arc-1473): adjust patch call logic

ui/src/react-admin/modules/shared/components/ContentPicker/ContentPicker.tsx
https://meemoo.atlassian.net/browse/ARC-1492
before:
after:
=> fix(arc-1492): remove test text input in navigations edit

ui/src/react-admin/modules/user-group/const/user-group.const.tsx, ui/src/react-admin/modules/user-group/views/UserGroupOverview.tsx
https://meemoo.atlassian.net/browse/AVO-2476
before:
order was determined by the number of permissions you have
after:
order is set in code by a const list
=> fix(avo-2476): set a fixed order for the user group columns

api/src/modules/content-pages/controllers/content-pages.controller.ts
**Jira**
https://meemoo.atlassian.net/browse/ARC-1411
=> fix(arc-1411): remove permissions for retrieval of content pages

api/src/modules/maintenance-alerts/controllers/maintenance-alerts.controller.spec.ts, api/src/modules/maintenance-alerts/controllers/maintenance-alerts.controller.ts, api/src/modules/maintenance-alerts/mocks/maintenance-alerts.mocks.ts
https://meemoo.atlassian.net/browse/ARC-1565
=> feat(arc-1565): omit maintenance alerts that have wrong dates set

ui/src/react-admin/modules/content-page/components/blocks/BlockThreeClickableTiles/BlockThreeClickableTiles.editorconfig.ts, ui/src/react-admin/modules/content-page/components/blocks/BlockThreeClickableTiles/BlockThreeClickableTiles.tsx, ui/src/react-admin/modules/content-page/types/content-block.types.ts
Ticket: https://meemoo.atlassian.net/browse/ARC-1168
Client PR: https://github.com/viaacode/hetarchief-client/pull/805
=> fix(three-tiles): remove title + add text ellipsis

ui/src/react-admin/modules/content-page/components/blocks/BlockImageGrid/BlockImageGrid.wrapper.tsx, ui/src/react-admin/modules/content-page/const/get-image-grid-format-options.ts, ui/src/react-admin/modules/content-page/types/content-block.types.ts
Ticket: https://meemoo.atlassian.net/browse/ARC-1441
Client PR: https://meemoo.atlassian.net/browse/ARC-1441
=> feat(BlockImageGrid): add format new format

ui/src/react-admin/modules/content-page/components/ContentEditForm/ContentEditForm.tsx
https://meemoo.atlassian.net/browse/ARC-1672
https://user-images.githubusercontent.com/77958553/236217287-d310a4a3-c459-4c36-9701-ce7aebafd521.mov
=> feat(ContentEditForm): add elvis operator

ui/src/react-admin/modules/shared/helpers/sanitize/presets/index.ts
https://meemoo.atlassian.net/browse/ARC-1679
Part of PR group:
- https://github.com/viaacode/react-admin-core-module/pull/178
- https://github.com/viaacode/hetarchief-client/pull/882
=> feat(presets): add hr to allowed richt text editor tags

ui/src/react-admin/modules/content-page/components/blocks/BlockThreeClickableTiles/BlockThreeClickableTiles.editorconfig.ts
https://meemoo.atlassian.net/browse/ARC-1674
https://user-images.githubusercontent.com/77958553/236752678-1c117f36-f291-4f8f-9400-fa90e8d0e294.mov
=> feat(BlockThreeClickableTiles): add missing content picker type

ui/src/react-admin/modules/content-page/components/blocks/BlockButtons/BlockButtons.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockEventbrite/BlockEventbrite.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockHero/BlockHero.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockImageTitleTextButton/BlockImageTitleTextButton.wrapper.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockMediaGrid/BlockMediaGrid.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockRichText/BlockRichText.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockRichText/BlockRichTextTwoColumns.editorconfig.ts, ui/src/react-admin/modules/content-page/components/blocks/BlockVideoTitleTextButton/BlockVideoTitleTextButton.wrapper.tsx
https://meemoo.atlassian.net/browse/ARC-1693
client PR:
https://github.com/viaacode/hetarchief-client/pull/887
=> fix(arc-1693): fix icons in the admin-core and content blocks

ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.wrapper.tsx
https://meemoo.atlassian.net/browse/ARC-1298?focusedCommentId=40801
https://github.com/viaacode/react-admin-core-module/assets/77958553/5190ecb4-3840-446d-be01-4a24f8694c01
=> feat(BlockPageOverview): scroll focused faq item into view

ui/src/react-admin/modules/content-page/components/blocks/BlockImageTextBackground/BlockImageTextBackground.editorconfig.ts, ui/src/react-admin/modules/content-page/components/blocks/BlockImageTextBackground/BlockImageTextBackground.tsx, ui/src/react-admin/modules/content-page/const/get-align-options.ts, ui/src/react-admin/modules/content-page/types/content-block.types.ts
https://meemoo.atlassian.net/browse/ARC-1307
=> feat(arc-1307): add 4 image alignment options to text with background

ui/src/react-admin/modules/translations/views/TranslationsOverview.tsx
https://meemoo.atlassian.net/browse/ARC-1714
do not save search field text in url, since it causes rerenders that cause the cursor to jump to the end of the input field
before:
user presses backspace and cursor jumps to the end:
=> fix(arc-1714): fix search field in translations overview

ui/src/react-admin/modules/content-page/components/blocks/BlockCardsWithoutDescription/BlockCardsWithoutDescription.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockMaintainersGrid/BlockMaintainersGrid.tsx
https://meemoo.atlassian.net/browse/ARC-1169
https://github.com/viaacode/react-admin-core-module/assets/1710840/36e2ba1a-af4e-438f-bc5d-a4a40abe609d
=> feat(arc-1169): pick 14 maintainers at random when the block loads

ui/src/react-admin/modules/content-page/components/blocks/BlockMaintainersGrid/BlockMaintainersGrid.editorconfig.ts, ui/src/react-admin/modules/content-page/components/blocks/BlockMaintainersGrid/BlockMaintainersGrid.tsx, ui/src/react-admin/modules/content-page/types/content-block.types.ts, ui/src/shared/translations/avo/nl.json, ui/src/shared/translations/hetArchief/nl.json
https://meemoo.atlassian.net/browse/ARC-1169
=> feat(arc-1169): add number of items option to maintainers block

api/src/modules/organisations/admin-organisations.types.ts, api/src/modules/organisations/queries/avo/get-organisation.graphql, api/src/modules/organisations/queries/hetarchief/get-organisation.graphql, api/src/modules/organisations/queries/hetarchief/get-organisations.graphql, api/src/modules/organisations/queries/organization.queries.ts, api/src/modules/organisations/services/admin-organisations.service.spec.ts, api/src/modules/organisations/services/admin-organisations.service.ts, api/src/modules/shared/generated/graphql-db-types-avo.ts, api/src/modules/shared/generated/graphql-db-types-hetarchief.ts, api/src/modules/users/users.service.ts, ui/src/react-admin/modules/user/hooks/use-get-profiles.ts, ui/src/react-admin/modules/user/views/UserOverview.tsx
https://meemoo.atlassian.net/browse/ARC-1536
before:
after:
=> fix(arc-1536): load organisations from org table instead of maintainers

ui/src/react-admin/modules/content-page/components/blocks/BlockImageGrid/BlockImageGrid.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockImageGrid/BlockImageGrid.types.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockImageGrid/BlockImageGrid.wrapper.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockImageGrid/BlockLogoGrid.editorconfig.ts, ui/src/react-admin/modules/content-page/components/blocks/BlockImageGrid/BlockLogoGrid.wrapper.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockImageGrid/BlockUspGrid.wrapper.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.tsx, ui/src/react-admin/modules/content-page/const/get-image-grid-format-options.ts, ui/src/react-admin/modules/content-page/types/content-block.types.ts
https://meemoo.atlassian.net/browse/ARC-1240
client PR: https://github.com/viaacode/hetarchief-client/pull/994
https://github.com/viaacode/react-admin-core-module/assets/1710840/5e307820-756f-475b-a7b3-118520efc12e
=> feat(arc-1240): add image grid option: 30 percent wide

api/src/modules/translations/services/translations.service.ts
https://meemoo.atlassian.net/browse/ARC-1875
matching change in the client:
https://github.com/viaacode/hetarchief-client/pull/1027
=> fix(arc-1875): change caching to 30 minutes on the proxy

api/package-lock.json, api/package.json, api/src/modules/assets/assets.consts.ts, api/src/modules/assets/controllers/assets.controller.ts, api/src/modules/content-pages/controllers/content-pages.controller.ts, api/src/modules/shared/decorators/user.decorator.ts, api/src/modules/users/classes/session-user.ts, ui/src/react-admin/modules/shared/components/FileUpload/FileUpload.tsx, ui/src/react-admin/modules/shared/components/Loader/Loader.tsx, ui/src/react-admin/modules/shared/helpers/files.ts
https://meemoo.atlassian.net/browse/ARC-1962
- 2MB gif (animated) => 551KB animated webp  (74% smaller)
- 3.85 MB jpg => 1.58MB webp (59% smaller)
- 453KB jpg => 185KB webp (59% smaller)
- 2.23MB png => 124KB webp (94% smaller)
=> feat(arc-1962): convert uploaded images to webp to reduce filesize

ui/src/react-admin/modules/content-page/components/blocks/BlockSpotlight/BlockProjectSpotlight.wrapper.tsx, ui/src/react-admin/modules/content-page/services/content-page.service.ts
https://meemoo.atlassian.net/browse/AVO-2453
before:
after:
=> fix(AVO-2453): load contentPages for spotlight from admin-core-api

api/src/modules/users/users.controller.ts, api/src/modules/users/users.types.ts, ui/src/react-admin/modules/user/user.service.ts
https://meemoo.atlassian.net/browse/AVO-2442
=> fix(AVO-2442): find users as post endpoint to avoid max url length

ui/src/react-admin/modules/content-page/helpers/get-published-state.ts
Ticket: https://meemoo.atlassian.net/browse/AVO-3036
=> fix(avo-3036): check timebound first

ui/src/react-admin/modules/alerts/views/AlertsOverview.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockKlaar/BlockKlaar.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockUitgeklaard/BlockUitgeklaard.tsx
https://meemoo.atlassian.net/browse/AVO-3098
=> fix(AVO-3098): adjust date-fns formatting to be more verbose

ui/src/react-admin/modules/user/components/TempAccessModal.tsx
https://meemoo.atlassian.net/browse/AVO-3114
Requires https://github.com/viaacode/avo2-client/pull/1961
=> fix(AVO-3114): switch to existing datepicker

api/package-lock.json, api/package.json, package-lock.json, package.json, ui/package-lock.json, ui/package.json, ui/src/react-admin/modules/content-page/components/blocks/BlockMediaGrid/BlockMediaGrid.editorconfig.ts, ui/src/react-admin/modules/content-page/helpers/validate-content-block-config.ts, ui/src/react-admin/modules/content-page/views/ContentPageEdit.tsx, ui/src/react-admin/modules/shared/components/ContentPicker/ContentPicker.tsx, ui/src/react-admin/modules/shared/components/ContentPicker/helpers/parse-picker.ts
https://meemoo.atlassian.net/browse/AVO-3113
=> bugfix(AVO-3113): adjust search query validation and add global validation for block fields

api/.gitignore, api/src/modules/shared/generated/graphql-db-types-avo.ts, api/src/modules/shared/generated/graphql-db-types-hetarchief.ts, api/src/modules/translations/controllers/translations.controller.spec.ts, api/src/modules/translations/controllers/translations.controller.ts, api/src/modules/translations/dto/translations.dto.ts, api/src/modules/translations/index.ts, api/src/modules/translations/queries/hetarchief-and-avo/getAllLanguages.graphql, api/src/modules/translations/services/translations.service.spec.ts, api/src/modules/translations/services/translations.service.ts, api/src/modules/translations/translations.module.ts, api/src/modules/translations/translations.types.ts
https://meemoo.atlassian.net/wiki/spaces/HA2/pages/4212817944/TA+meertaligheid#admin-core-api-Voeg-een-endpoint-toe-om-alle-talen-op-te-halen
=> feat(languages): add languages endpoint

api/src/modules/assets/queries/hetarchief-and-avo/getContentAsset.graphql, api/src/modules/assets/queries/hetarchief-and-avo/updateContentAsset.graphql, api/src/modules/assets/services/assets.service.ts, api/src/modules/shared/generated/graphql-db-types-hetarchief.ts
https://meemoo.atlassian.net/browse/ARC-2199
otherwise we get:
```
Uniqueness violation. duplicate key value violates unique constraint "content_assets_path_key"
```
=> feat(ARC-2199): insert or update assets for sitemap.xml

api/src/modules/shared/generated/graphql-db-types-hetarchief.ts, api/src/modules/translations/services/translations.service.ts, ui/src/react-admin/core/config/config.types.ts, ui/src/react-admin/modules/content-page-labels/views/ContentPageLabelDetail.tsx, ui/src/react-admin/modules/content-page-labels/views/ContentPageLabelEdit.tsx, ui/src/react-admin/modules/content-page-labels/views/ContentPageLabelOverview.tsx, ui/src/react-admin/modules/content-page/components/ContentEditForm/ContentEditForm.tsx, ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.wrapper.tsx, ui/src/react-admin/modules/content-page/const/content-page.consts.ts, ui/src/react-admin/modules/content-page/views/ContentPageDetail.tsx, ui/src/react-admin/modules/content-page/views/ContentPageDetailMetaData.tsx, ui/src/react-admin/modules/index.ts, ui/src/react-admin/modules/maintenance-alerts/views/MaintenanceAlertsEditForm.tsx, ui/src/react-admin/modules/maintenance-alerts/views/MaintenanceAlertsOverview.tsx, ui/src/react-admin/modules/navigation/components/NavigationEditForm/NavigationEditForm.tsx, ui/src/react-admin/modules/navigation/hooks/use-get-navigation-bar-items.ts, ui/src/react-admin/modules/navigation/views/NavigationBarDetail.tsx, ui/src/react-admin/modules/navigation/views/NavigationItemEdit.tsx, ui/src/react-admin/modules/shared/components/ContentPicker/item-providers/internal-link.ts, ui/src/react-admin/modules/shared/components/FilterTable/FilterTable.tsx, ui/src/react-admin/modules/shared/helpers/is-multi-language-enabled.ts, ui/src/react-admin/modules/shared/helpers/render-detail-fields.tsx, ui/src/react-admin/modules/shared/types/table-filter-types.ts, ui/src/react-admin/modules/user/user.consts.ts, ui/src/react-admin/modules/user/views/UserDetail.tsx
https://meemoo.atlassian.net/browse/ARC-2096
=> feat(ARC-2096): integrate multilanguage admin-core

ui/src/react-admin/modules/shared/components/ExportAllToCsvModal/ExportAllToCsvModal.tsx, ui/src/react-admin/modules/shared/helpers/react-node-to-string.tsx, ui/src/react-admin/modules/user/views/UserOverview.tsx
https://meemoo.atlassian.net/browse/AVO-3339
part of PR group:
* https://github.com/viaacode/react-admin-core-module/pull/281
* https://github.com/viaacode/avo2-proxy/pull/777
* https://github.com/viaacode/avo2-client/pull/2077
=> fix(AVO-3339): omit "-" empty values, improve html stripping, comma sep
