demo/src/index.tsx
demo/src/react-admin/core/config/config.types.ts
demo/src/react-admin/modules/navigation/components/NavigationEditForm/NavigationEditForm.tsx
demo/src/react-admin/modules/navigation/views/NavigationEdit.tsx

So we can hide the icon selection for hetarchief

feat(arc-591): Add enable icons option for navigation bars

---

ui/src/react-admin/modules/navigation/views/NavigationEdit.tsx

This PR fixes the filled in formstate when creating a new navigation item after editing an existing one. Check out the video's to see the difference.
[Bugged flow - before the fix](https://user-images.githubusercontent.com/77958553/213181817-f55c530d-5f32-4c0e-9aaa-c7f970e08d7d.mov)
[Desired behaviour - after the fix](https://user-images.githubusercontent.com/77958553/213181840-8f648646-32cf-4205-96e3-b0ef0a7502ac.mov)

feat: only update the formstate for existing items

---

api/src/modules/content-page-labels/content-page-labels.controller.ts
api/src/modules/content-pages/controllers/content-pages.controller.ts
api/src/modules/items/items.controller.ts

Some routes still needed permissions to be checked.
These routes replace graphql queries that were run directly in the avo2-client en were sent to the graphql database via the /data endpoint on the avo2-proxy. The permission checking system for the /data route is quite convoluted, so we hope to someday get rid of it completely.

feat(permissions): move permission checks from proxy to admin-core-api

---

ui/src/react-admin/modules/shared/components/IconPicker/IconPicker.tsx

This PR is related to https://github.com/viaacode/hetarchief-client/pull/613.
Make sure to use the configured icon component for the iconpicker component. 
This functionality is needed to be able to render all configured icons correctly.

feat(IconPicker): render icons using the configured icon component

---

ui/src/index.tsx
ui/src/react-admin/core/config/config.types.ts
ui/src/react-admin/modules/content-page/views/ContentPageDetail.tsx
ui/src/react-admin/modules/content-page/views/ContentPageEdit.tsx
ui/src/react-admin/modules/navigation/views/NavigationDetail.tsx
ui/src/react-admin/modules/navigation/views/NavigationEdit.tsx
ui/src/react-admin/modules/user/views/UserDetail.tsx
ui/src/react-admin/modules/user/views/UserEdit.tsx

https://meemoo.atlassian.net/browse/AVO-2375
page:
* http://localhost:8080/admin/gebruikers/a900a663-c319-4b3c-99da-ede663ad29fc
* http://localhost:8080/admin/gebruikers/a900a663-c319-4b3c-99da-ede663ad29fc/bewerk
* http://localhost:8080/admin/content/1529
* http://localhost:8080/admin/content/1529/bewerk
* http://localhost:8080/admin/navigatie/footer-links
* http://localhost:8080/admin/navigatie/footer-links/1/bewerk
before:
after:

fix(avo-2375): add back buttons to users, content pages, navigations

---

api/src/modules/content-pages/services/content-pages.service.ts
ui/src/react-admin/modules/content-page/services/content-page.service.ts
ui/src/react-admin/modules/content-page/views/ContentPageOverview.tsx
ui/src/react-admin/modules/shared/components/ContentPicker/item-providers/content-page.ts

https://meemoo.atlassian.net/browse/AVO-2416
page:
* http://localhost:3400/admin/content
* http://localhost:3400/admin/content/1585
before:
after:
before:
after:

fix(avo-2416): delete id before trying to duplicate a content page

---

ui/src/react-admin/modules/content-page/components/ContentEditForm/ContentEditForm.tsx
ui/src/react-admin/modules/content-page/helpers/content-edit.reducer.ts
ui/src/react-admin/modules/content-page/types/content-pages.types.ts

https://meemoo.atlassian.net/browse/AVO-2410
page: http://localhost:3400/admin/content/1586/bewerk
before:
when entering a description for a content page
saving
and again editing the content page, the description rich text editor would be empty.
after:

fix(avo-2410): fix loading contentPage description into rich text editor

---

ui/package-lock.json
ui/package.json

https://meemoo.atlassian.net/browse/AVO-2433
bumps version of the avo2-components to include pagination icons fix:
https://github.com/viaacode/avo2-components/commit/a16f32b1fd2250a19c3074dcd47f9f21c9ef0d7e

fix(avo-2433): fix first and last page icons in pagination control

---

ui/src/react-admin/modules/content-page/components/ContentBlockRenderer/ContentBlockRenderer.tsx

https://meemoo.atlassian.net/browse/ARC-1448
For some of the content blocks we want to be able to add specific styling. This PR adds a class to each content block based on its type which will make styling easier:

feat(arc-1448): add content block class for each content block type

---

ui/src/react-admin/modules/content-page/components/blocks/BlockSpotlight/BlockProjectSpotlight.wrapper.tsx
ui/src/react-admin/modules/content-page/components/blocks/BlockSpotlight/BlockSpotlight.tsx
ui/src/react-admin/modules/shared/components/FileUpload/FileUpload.tsx

https://meemoo.atlassian.net/browse/AVO-2453
example: http://localhost:3400/admin/content/1642
A spotlight block is a block where you can select 3 content pages to be displayed.
If one of those content pages is deleted, the whole block fails:
This PR makes the spotlight block fault tolerant:
If a page is not found, it will show a message: Pagina niet gevonden, with the path to the missing page, so a meemoo admin can resolve the issue.
I also fixed an issue if a cover image was deleted on the server, we were not able to delete it anymore from a content page. Now if there is an issue with the delete from the server, we still allow the user to continue editing the content page by deleting the cover url to the faulty image from the content page.
Note that uploading images in the admin-core …

AVO-2453 Allow not found content pages in spotlight block

---

ui/src/index.tsx
ui/src/react-admin/modules/user/views/UserOverview.tsx

https://meemoo.atlassian.net/browse/AVO-2442
When someone selects all users on production and tries to export them, this is too heavy and the request fails.
But the users remain selected, so all subsequent exports fail
This PR clears the selected users list after a succesful and after a failed export to avoid this issue.

fix(avo-2442): de-select users when an error is occurred during export

---

ui/src/react-admin/modules/navigation/hooks/use-get-navigation-bar-items.ts
ui/src/react-admin/modules/navigation/navigation.types.ts
ui/src/react-admin/modules/navigation/views/NavigationEdit.tsx
ui/src/react-admin/modules/navigation/views/NavigationOverview.tsx
ui/src/shared/translations/hetArchief/nl.json

https://meemoo.atlassian.net/browse/ARC-1483
We don't want to allow meemoo to add navigation bars, only items on existing navigation bars.
Since adding a navigation bar requires dev changes in the frontend
before:
after:

fix(arc-1483): remove the navigation bar add button

---

ui/src/react-admin/modules/content-page/components/blocks/BlockImageGrid/BlockImageGrid.tsx

[AVO-2401](https://meemoo.atlassian.net/browse/AVO-2401)
Fix:
Adjust grid item component key to prevent duplicates being rendered
[AVO-2401]: https://meemoo.atlassian.net/browse/AVO-2401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2401): Adjust component key to prevent duplicates being rendered

---

ui/src/react-admin/modules/content-page/services/content-page.service.ts

[AVO-2354](https://meemoo.atlassian.net/browse/AVO-2354)
[AVO2-Proxy PR](https://github.com/viaacode/avo2-proxy/pull/603)
Fix: Use duplicate content page images function and adjust route for duplicate request in content page service
[AVO-2354]: https://meemoo.atlassian.net/browse/AVO-2354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(avo-2354): Fix image deletion issue on duplication of content page

---

ui/src/react-admin/modules/content-page/components/blocks/BlockThreeClickableTiles/BlockThreeClickableTiles.editorconfig.ts
ui/src/react-admin/modules/content-page/components/blocks/BlockThreeClickableTiles/BlockThreeClickableTiles.tsx
ui/src/react-admin/modules/content-page/types/content-block.types.ts

https://meemoo.atlassian.net/browse/ARC-1676
https://meemoo.atlassian.net/browse/ARC-1677
https://meemoo.atlassian.net/browse/ARC-1678
Extra changes (WCAG/A11Y):
- added a heading type selector since we can't know the outline structure which means we can't use a fixed heading element.
- render the image as an actual image asset instead of a background
This PR is part of a group of PRs:
- https://github.com/viaacode/hetarchief-client/pull/875
- https://github.com/viaacode/react-admin-core-module/pull/176
https://user-images.githubusercontent.com/77958553/236777899-1f84c00e-98d8-46a2-bb36-db111df63436.mov

feat(BlockThreeClickableTiles): add heading type + tweak html outline

---

ui/src/react-admin/modules/content-page/components/ContentBlockRenderer/ContentBlockRenderer.tsx
ui/src/react-admin/modules/content-page/components/ContentPageRenderer/ContentPageRenderer.scss
ui/src/react-admin/modules/content-page/components/blocks/defaults.ts
ui/src/react-admin/modules/content-page/const/get-color-options.ts
ui/src/react-admin/modules/content-page/types/content-block.types.ts

https://meemoo.atlassian.net/browse/ARC-1737
content blocks should now be displayed correctly on safari 15.x

fix(arc-1737): fix content block margin collapse on safari

---

ui/src/react-admin/core/config/config.types.ts
ui/src/react-admin/modules/alerts/views/AlertsOverview.tsx
ui/src/react-admin/modules/content-page/components/blocks/BlockHetArchiefHeaderSearch/BlockHetArchiefHeaderSearch.tsx
ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.wrapper.tsx
ui/src/react-admin/modules/content-page/helpers/field-attributes.ts
ui/src/react-admin/modules/shared/components/Icon/Icon.tsx

https://meemoo.atlassian.net/browse/ARC-1443
before:
after:

fix(arc-1443): sort page overview labels according to entry order

---

ui/src/react-admin/modules/content-page-labels/content-page-label.service.ts

https://meemoo.atlassian.net/browse/ARC-1748
before:
after:

fix(arc-1748): strip content page label fields before trying to update

---

ui/src/react-admin/modules/content-page/components/blocks/BlockCardsWithoutDescription/BlockCardsWithoutDescription.editorconfig.ts
ui/src/react-admin/modules/content-page/components/blocks/BlockCardsWithoutDescription/BlockCardsWithoutDescription.tsx

https://meemoo.atlassian.net/browse/ARC-1306
add option to add link to tiles and scale tiles to fix available space
before:
after:

fix(arc-1306): add link to cards without description block + scaling

---

api/src/modules/content-page-labels/dto/content-page-label.dto.ts
ui/src/react-admin/modules/content-page-labels/views/ContentPageLabelEdit.tsx
ui/src/shared/translations/avo/nl.json
ui/src/shared/translations/hetArchief/nl.json

Ticket: https://meemoo.atlassian.net/browse/ARC-1748

fix(arc-1748): link_to type is not string + label change

---

api/src/modules/shared/generated/graphql-db-types-avo.ts
api/src/modules/users/queries/avo/get-content-counts-for-users.graphql
api/src/modules/users/users.service.ts
api/src/modules/users/users.types.ts
ui/src/react-admin/modules/user/components/UserDeleteModal.tsx
ui/src/react-admin/modules/user/user.service.ts
ui/src/react-admin/modules/user/user.types.ts

https://meemoo.atlassian.net/browse/AVO-2677
also count collection/assignments that are shared with collaborators as public collections/assignments in the warning modal

fix(avo-2677): show public and private assignment counts for user delete

---

ui/src/react-admin/modules/shared/components/UserGroupSelect/UserGroupSelect.tsx

https://meemoo.atlassian.net/browse/ARC-1999
before:
after:

fix(ARC-1999): sort user groups in specific order

---

ui/src/react-admin/modules/alerts/views/AlertsOverview.tsx
ui/src/react-admin/modules/shared/helpers/formatters/date.ts

Current time:
- <img width="127" alt="image" src="https://github.com/viaacode/react-admin-core-module/assets/113892598/81d691a3-eb91-455c-b973-11a834b12ca3">
- <img width="1106" alt="image" src="https://github.com/viaacode/react-admin-core-module/assets/113892598/cc3ff542-9924-4e64-b7d8-d6801a5c4e3a">
- <img width="431" alt="image" src="https://github.com/viaacode/react-admin-core-module/assets/113892598/6b20b0e4-7945-463a-ab76-4017155b700d">
Ticket: https://meemoo.atlassian.net/browse/ARC-2013

fix(arc-2013): convert to BE time to show correct status

---

ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.wrapper.tsx
ui/src/react-admin/modules/shared/helpers/query-string-converters.ts

https://meemoo.atlassian.net/browse/AVO-2987
the issue was with the combination of the anchor block and the page overview block on a single page
page overview block would set ?label= on the url, even though the value was empty
the anchor link block would navigate to #inspiratie, after which the page overview block would again set ?label=
But if the value of label is empty it shouldn't be present in the url at all
it also helps to reproduce the issue on QAS, since then you can identify that the anchor block by itself works correctly.
eg: http://localhost:3400/admin/content/221
example of probelmatic page on qas:
http://localhost:3400/admin/content/2196
before:
after:

fix(AVO-2987): don't set label query param if value is empty

---

ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.tsx
ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.wrapper.tsx

https://meemoo.atlassian.net/browse/AVO-3032
my steps to debug content block issues:
* reproduce it on qas: https://onderwijs-qas.hetarchief.be/admin/content/222
* its a content block issue, so see if you can reproduce it on the admin-core alone for the same QAS page: http://localhost:3400/admin/content/222
* We can, so it is an admin-core only bug
* investigate the url: it has a double leading slash
* ![image](https://github.com/viaacode/react-admin-core-module/assets/1710840/da648dab-c1a2-47cf-92fc-0558cc295ed9)
* find the location where the link is created:
* search for the class that ends with -block higher up in the hierarchy:
* or search for the class of the label: c-content-page__label
* the link always gets a slash appended, but if it already has one, it creates a double slash => …

fix(AVO-3032): ensure page overview block labels are linked correctly

---

ui/src/react-admin/modules/content-page/components/blocks/BlockImage/BlockImage.editorconfig.ts
ui/src/react-admin/modules/content-page/components/blocks/BlockImage/BlockImage.scss
ui/src/react-admin/modules/content-page/components/blocks/BlockImage/BlockImage.tsx
ui/src/react-admin/modules/shared/components/SmartLink/SmartLink.tsx

https://meemoo.atlassian.net/browse/AVO-3021

feat(AVO-3021): add link options to image block

---

ui/src/react-admin/modules/content-page/components/blocks/BlockImage/BlockImage.editorconfig.ts
ui/src/react-admin/modules/content-page/types/content-block.types.ts

https://meemoo.atlassian.net/browse/AVO-3021
before:
after:

fix(AVO-3021): set default button alignment on image block

---

ui/src/react-admin/modules/content-page/components/ContentBlockForm/ContentBlockForm.tsx
ui/src/react-admin/modules/content-page/components/DraggableList/DraggableList.scss
ui/src/react-admin/modules/content-page/components/DraggableList/DraggableList.tsx
ui/src/react-admin/modules/content-page/views/ContentEditContentBlocks.scss
ui/src/react-admin/modules/content-page/views/ContentEditContentBlocks.tsx

https://meemoo.atlassian.net/browse/AVO-3104
fix text cursor jumps to end, by only rendering drag and drop wrapper if all block accordions are collapsed:
https://github.com/viaacode/react-admin-core-module/assets/1710840/3c09bdc0-fa56-4df4-a6be-fac24eac93bd
fix scroll to:
https://github.com/viaacode/react-admin-core-module/assets/1710840/97c24f6f-4d31-4f8c-8425-8b4a0e06d24f

fix(AVO-3104): only enable drag-and-drop when all accordions are closed

---

ui/src/react-admin/modules/shared/components/ContentPicker/helpers/parse-picker.ts

https://meemoo.atlassian.net/browse/AVO-3113
Mirror of https://github.com/viaacode/avo2-client/pull/1951

fix(AVO-3113): return empty instead of untranslated string

---

api/src/modules/content-pages/controllers/content-pages.controller.ts
ui/src/react-admin/modules/shared/components/UserGroupSelect/UserGroupSelect.tsx

https://meemoo.atlassian.net/browse/ARC-1999
before:
after:
ideally we would save the display order somewhere in the database. But for now there isn't any budget for that, since the order changed without meemoo's request

fix(ARC-1999): sort user groups according to preferred order for avo

---

api/src/modules/assets/controllers/assets.controller.ts

https://meemoo.atlassian.net/browse/AVO-3147
image should be uploaded with the correct type:
When deleting an image something seems to go wrong with the user permissions check of the session user class.

fix(AVO-3147): upload imgs with correct type, check perm. for delete

---

api/src/mock-user.ts
api/src/modules/assets/controllers/assets.controller.spec.ts
api/src/modules/assets/controllers/assets.controller.ts
api/src/modules/content-page-labels/dto/content-page-label.dto.ts
api/src/modules/content-page-labels/mocks/content-page-labels.mocks.ts
api/src/modules/content-pages/content-pages.types.ts
api/src/modules/content-pages/controllers/content-pages.controller.ts
api/src/modules/content-pages/services/content-pages.service.ts
api/src/modules/maintenance-alerts/dto/maintenance-alerts.dto.ts
api/src/modules/maintenance-alerts/maintenance-alerts.types.ts
api/src/modules/maintenance-alerts/services/maintenance-alerts.service.ts
api/src/modules/navigations/controllers/admin-navigations.controller.spec.ts
api/src/modules/navigations/controllers/admin-navigations.controller.ts
api/src/modules/navigations/dto/navigations.dto.ts
api/src/modules/navigations/navigations.types.ts
api/src/modules/navigations/services/admin-navigations.service.spec.ts
api/src/modules/navigations/services/admin-navigations.service.ts
api/src/modules/shared/helpers/translation-fallback.ts
api/src/modules/status/services/status.service.ts
api/src/modules/translations/controllers/translations.controller.ts
api/src/modules/translations/dto/translations.dto.ts
api/src/modules/translations/services/translations.service.spec.ts
api/src/modules/translations/services/translations.service.ts
api/src/modules/translations/translations.types.ts
api/src/modules/users/classes/session-user.ts
ui/src/react-admin/core/config/config.types.ts

https://meemoo.atlassian.net/browse/ARC-2117
part of a PR group:
* https://github.com/viaacode/react-admin-core-module/pull/258
* https://github.com/viaacode/hetarchief-client/pull/1146
* https://github.com/viaacode/hetarchief-proxy/pull/479
also renamed LanguageCode to Locale in admin-core-api

fix(ARC-2117): add locale to tText function in admin-core-api

---

ui/src/react-admin/modules/maintenance-alerts/views/MaintenanceAlertsEditForm.tsx

https://meemoo.atlassian.net/browse/ARC-2110

fix(ARC-2110): correctly load language field in maintenance alerts blade

---

ui/src/react-admin/modules/content-page/components/blocks/BlockEventbrite/BlockEventbrite.tsx

Steps to reproduce issue:
1. https://onderwijs-qas.hetarchief.be/workshops-en-events/webinars
2. open any detail page
3. press the register now button
4. cancel the registration
5. scroll to the bottom
6. press the return to overview button
7. open a different detail page
8. press the register now button again

fix(AVO-3142): ensure eventbrite can re-initialize on subsequent navigation

---

ui/src/react-admin/core/config/config.class.ts
ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.scss
ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.tsx
ui/src/react-admin/modules/content-page/components/blocks/BlockPageOverview/BlockPageOverview.wrapper.tsx

https://meemoo.atlassian.net/browse/ARC-2470

fix(ARC-2470): avoid crash when overview block link doesn't exist

---

ui/src/react-admin/modules/content-page/views/ContentPageDetail.tsx

https://meemoo.atlassian.net/browse/ARC-2453
We need to use the language of the page, not the language of the website
also do not add language in the url if the page language is dutch
dutch:
english:

fix(ARC-2453): fix preview path for content pages for multilanguage
